if has("gui_macvim")
    set transp=2
    set guioptions-=T
    set autochdir
    set guifont=Menlo\ Regular:h13
    colorscheme zenburn
    macmenu &File.New\ Tab key=<nop>
    map <D-t> :CommandT<CR>
endif
