(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
(defun my-org-dict-replace ()
  (interactive)
  (backward-word)
  (search-forward (current-word))
  (replace-match (concat "[[dict://" (current-word) "][" (current-word) "]]")))
(defun my-look-up-word ()
  (interactive)
  (shell-command (concat "open dict://" (current-word))))
(add-hook 'org-mode-hook
          (lambda ()
            (flyspell-mode)
            (yas/minor-mode-on)
            (local-set-key (kbd "s-i") 'my-org-dict-replace)
            (local-set-key (kbd "s-r")
                           (lambda ()
                             (interactive)
                             (shell-command (concat "open dict://" (current-word)))))))
(setq org-startup-indented t)
(org-add-link-type "dict" 'org-dict-open)
(defun org-dict-open (path)
  (shell-command (concat "open dict:" path)))
(setq org-directory "~/Documents/org/")
